
services:
  media-parser-backend:
    build: .
    container_name: media-parser-backend
    restart: always
    networks:
      - shared-network  # 改为共享网络
    ports:
      - "8051:8051"
    volumes:
      # 将宿主机上的日志、静态视频目录映射，以便容器删除和重建时不丢失数据或便于排查问题
      - ./static/videos:/app/static/videos
      - ./logs:/app/logs
    # 设置容器内的时区为本地时区
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-rDl9zfGPFvXcYBY5Cmlh}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-294SLh9j7uIJYxoaGCG8asT3W52pq8PXNePZ0ltJ}
      - MINIO_BUCKET=${MINIO_BUCKET:-ink-away}
      - MINIO_DOWNLOAD_URL=${MINIO_DOWNLOAD_URL:-https://img.cleancoder.xyz/}
    # 限制日志大小，防止生产环境磁盘爆满 (Log Rotation)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared-network:
    external: true # 使用外部网络